# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(483, 301)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Form.setFont(font)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 131, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.thread_count = QtWidgets.QSpinBox(self.layoutWidget)
        self.thread_count.setMinimum(1)
        self.thread_count.setMaximum(256)
        self.thread_count.setProperty("value", 128)
        self.thread_count.setObjectName("thread_count")
        self.horizontalLayout_2.addWidget(self.thread_count)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 421, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(19)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.url_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.url_input.setObjectName("url_input")
        self.horizontalLayout.addWidget(self.url_input)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 160, 423, 121))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.startButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_3.addWidget(self.startButton)
        self.open_folderButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.open_folderButton.setObjectName("open_folderButton")
        self.horizontalLayout_3.addWidget(self.open_folderButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progress_text = QtWidgets.QLabel(self.layoutWidget2)
        self.progress_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progress_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.progress_text.setObjectName("progress_text")
        self.horizontalLayout_4.addWidget(self.progress_text)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.detail_label = QtWidgets.QLabel(self.layoutWidget2)
        self.detail_label.setText("")
        self.detail_label.setWordWrap(True)
        self.detail_label.setObjectName("detail_label")
        self.verticalLayout.addWidget(self.detail_label)
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 50, 421, 24))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(19)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.file_name = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.file_name.setObjectName("file_name")
        self.horizontalLayout_8.addWidget(self.file_name)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "M3U8下载器"))
        self.label_3.setText(_translate("Form", "开启线程数:"))
        self.label.setText(_translate("Form", "URL:"))
        self.url_input.setPlaceholderText(_translate("Form", "m3u8文件下载地址"))
        self.startButton.setText(_translate("Form", "开始"))
        self.open_folderButton.setText(_translate("Form", "打开文件夹"))
        self.progress_text.setText(_translate("Form", "0/0"))
        self.label_6.setText(_translate("Form", "保存文件名:"))
        self.file_name.setPlaceholderText(_translate("Form", "文件名"))
